name: C Project CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          libcurl4-openssl-dev \
          libjson-c-dev \
          libgtest-dev \
          libgmock-dev \
          gcc \
          g++ \
          git \
          pkg-config \
          libssl-dev

    - name: Update submodule (open62541)
      run: |
        git submodule update --init --recursive  # Zaktualizuj submoduł open62541

    - name: Build open62541
      run: |
        cd open62541
        mkdir -p build
        cd build
        cmake ..
        make
        sudo make install  # Zainstaluj open62541

    - name: Build project
      run: |
        touch .env
        make build

    - name: Run tests
      run: |
        make run_tests
